stages:
  - test

variables:
  MYSQL_DATABASE: obj_detect_test_db
  APP_ENV: ai_env

run_tests:
  image: python:3.11  # use latest stable python version
  stage: test
  script:
    - echo "Running tests"
    - python -m venv $APP_ENV        # Create virtual environment
    - source $APP_ENV/bin/activate   # Activate environment
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - export OBJ_DETECT_ENV=test
    - export OBJ_DETECT_MYSQL_DB=$MYSQL_DATABASE
    - python3 -m unittest discover
    - deactivate
